# Generated by Django 3.2.18 on 2023-06-23 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president_clubs', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_clubs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('seat_number', models.CharField(max_length=50)),
                ('student_name', models.CharField(max_length=100)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('original_club_teacher_approved', models.BooleanField(null=True)),
                ('original_club_president_approved', models.BooleanField(null=True)),
                ('desired_club_teacher_approved', models.BooleanField(null=True)),
                ('desired_club_president_approved', models.BooleanField(null=True)),
                ('original_club_teacher_approved_time', models.DateTimeField(null=True)),
                ('original_club_president_approved_time', models.DateTimeField(null=True)),
                ('desired_club_teacher_approved_time', models.DateTimeField(null=True)),
                ('desired_club_president_approved_time', models.DateTimeField(null=True)),
                ('desired_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desired_transfers', to='transferapp.club')),
                ('original_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_transfers', to='transferapp.club')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
                ('seat_number', models.IntegerField()),
                ('student_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transferapp.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
