# Generated by Django 3.2.18 on 2023-06-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transferapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferFormSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='填寫開始時間')),
                ('end_time', models.DateTimeField(verbose_name='填寫結束時間')),
            ],
        ),
    ]
